### ISSUE TITLE
Identifier "Serial" is undefined!

### ISSUE THREAD

**Issue by kakaooo** [yeacreate-opensources/Nscreen_32#1]
I'm having an issue on using the Arduino commands into this Nscreen32 board. When i try to use the Serial.begin or any Serial command the ide returns an error with "Serial is undefined." I googled it for a while and the problem might be solved with adding "USBCON" command into c_cpp_properties.json file. I did it but no help. 

However i tried to use tag parser to fix the error and there was something , the ide recognizes the command, leads the command to its header etc but the issue remains withing the compilation of the code.  What am i missing? Any idea on how to fix this?
![2021-06-21_16-18-45](https://user-images.githubusercontent.com/74058170/122771125-cf5c3080-d2ae-11eb-8862-2215b463ab0e.png)
![2021-06-21_15-52-47](https://user-images.githubusercontent.com/74058170/122771128-cff4c700-d2ae-11eb-8f55-1c71c6cede58.png)
![2021-06-21_15-52-23](https://user-images.githubusercontent.com/74058170/122771130-d08d5d80-d2ae-11eb-85b2-d00c971c42b3.png)

**Comment by simonchen007** [comment]
Please try this platformio.ini
https://github.com/yeacreate-opensources/Nscreen_32/blob/master/lvgl_demo/platformio.ini
You do not need to use USBCON. Serial.begin(9600) should be added to the setup().
Nscreen32 haven't got a real USB port. It's covered by a chip(CP2104), this chip is just cover the USB to the serial port of Nscreen32.

**Comment by kakaooo** [comment]
@simonchen007  I have been using this repository since i started with Nscreen. So my platformio.ini file contains the same commands. However i changed the .ini files yet the issue remains. I'm literally stucked on how to fix it.

**Comment by simonchen007** [comment]
@kakaooo  You wanna the Nscreen32 connect to the Arduino via Serial , right ?

**Comment by kakaooo** [comment]
@simonchen007  Yes, but not spesifically arduino. I want to use the serial communication of Nscreen32 to be able to communicate with any desired microcontroller. As far as i' ve checked there are two Serial ports on Nscreen32. My other functions are working just fine such as digitalWrite, pinMode etc.

**Comment by simonchen007** [comment]
@kakaooo  Okay, let me make you an example about Serial communication. Which example are you using currently in this repo: https://github.com/yeacreate-opensources/Nscreen_32/ ?

**Comment by kakaooo** [comment]
@simonchen007  I am not using any specific example. Created my own header and .c file and calling it from display_service.cpp. However your example would be appreciated anyways if you want to put it any of the repo examples that would work for me.

**Comment by kakaooo** [comment]
@simonchen007  Hey there, is there any update on the serial example?

**Comment by simonchen007** [comment]
here is a demo.
main.cpp
```c
/*

esp32 serial demo
===============================================

*/

#include <Arduino.h>


#define SERIAL_SPEED 115200

// int incomingByte = 0; // for incoming serial data
String str;

void setup()
{
  Serial.begin(SERIAL_SPEED);
  Serial.print(F("\n"));
  Serial.println(F("[INFO] YeaCreate Nscreen-32 Serial demo."));
}

void loop(void)
{
 if (Serial.available() > 0) {
    // read the incoming byte:
    // incomingByte = Serial.read();
    str = Serial.readString();

    // say what you got:
    Serial.print("I received: ");
    // Serial.println(incomingByte, DEC);
    Serial.println(str);
  }
}

```

And here is the test log:
```log
Welcome to minicom 2.7.1

OPTIONS: I18n 
Compiled on Dec 23 2019, 02:06:26.
Port /dev/ttyUSB0, 16:50:49

Press CTRL-A Z for help on special keys

ets Jul 29 2019 12:21:46

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:10124
load:0x40080400,len:5828
entry 0x400806a8

[INFO] YeaCreate Nscreen-32 Serial demo.
I received: aaa
I received: bbb
```

**Comment by kakaooo** [comment]
@simonchen007 Thanks for the guide, but the Serial command works in my main.cpp as well the problem is returned when any of the LVGL examples play the role. As far as i tracked the examples, they are called in display_service.cpp file. So i create my example and try to integrate with the diplay_service.cpp any other functions including the LVGL functions are working just fine. When it comes to the Serial command i get the error. Therefore, my problem lies within the GUI interface with the Serial communication. So any idea on how to communicate with other devices linked with my GUI commands?

**Comment by simonchen007** [comment]
@kakaooo  
1. the Serial.begin() must be in the setup() function in arduino.
2. here is anohter example.
https://github.com/yeacreate-opensources/Nscreen_32/blob/master/lvgl_demo/src/io_service.cpp
And
https://github.com/yeacreate-opensources/Nscreen_32/blob/master/lvgl_demo/src/main.cpp#L77
This example is with GUI interface. you can change the fllowing in main.cpp and try:
replace:
```c
void loop(void)
{
  feedTheDog();
}
```
to:
```c
void loop(void)
{
 if (Serial.available() > 0) {
    // read the incoming byte:
    // incomingByte = Serial.read();
    str = Serial.readString();

    // say what you got:
    Serial.print("I received: ");
    // Serial.println(incomingByte, DEC);
    Serial.println(str);
  }
}
```

**Comment by kakaooo** [comment]
Hey @simonchen007 thanks for the support, seems like we have fixed the problem. The method i used i am not sure exactly a correct method or not but works fine. 

Firstly, i defined my callback functions in a created demo.c file and for the display i call the function in display_service.cpp for the GUI application and for the communication i call the data function in main.cpp. Here is the method of the process;


![2021-06-25_16-30-44](https://user-images.githubusercontent.com/74058170/123432725-54a75400-d5d3-11eb-8d8d-6e7cab0aa477.png)

![2021-06-25_16-31-55](https://user-images.githubusercontent.com/74058170/123432724-54a75400-d5d3-11eb-9823-93935a126841.png)

![2021-06-25_16-32-43](https://user-images.githubusercontent.com/74058170/123432721-540ebd80-d5d3-11eb-9303-ff2b23682b1f.png)

![2021-06-25_16-33-38](https://user-images.githubusercontent.com/74058170/123432719-53762700-d5d3-11eb-9a36-f0fa2e36dc44.png)
