### ISSUE TITLE
Backlight Control

### ISSUE THREAD

**Issue by fvanroie** [yeacreate-opensources/Nscreen_32#2]
Does the board have a way to control the backlight brightness e.g. via GPIO or TFT command?

Thanks.

**Comment by simonchen007** [comment]
The backlight brightness is turn on by default. And it can not be consoled in this version. Because this parallel LCD display using too much GPIOs,  we do not have enought GPIO for brightness control.

**Comment by fvanroie** [comment]
That's a real shame, it will limit the number of applications for the board to backlight always-on devices only...

**Comment by simonchen007** [comment]
Thing is that, Nscreen32 is a board for developers. Performance , price and more GPIOs is more useful for developers. Actually we also provide customize service for commercal projects. We are using SPI interface(with a graphics accelerate chip) for commercal projects, and this can also bring about 8 GPIOs release, we can use those GPIOs for controling backlight and etc. If you interesting with the  customize service, please contract us via business@yeacreate.com
