### ISSUE TITLE
Update LVGL library

### ISSUE THREAD

**Issue by ajsb85** [yeacreate-opensources/Nscreen_32#3]

**Comment by simonchen007** [comment]
okay, we will make to plan to update the LVGL as LVGL8.x , will notice you once it done.

**Comment by mm108** [comment]
hi, is there any update on this?

**Comment by rillhu** [comment]
> hi, is there any update on this?
I made an update using lvgl 8.2, you could see below link as reference.
https://github.com/rillhu/Nscreen_32.git

And I also hope there will be offical update from Nscreen.

**Comment by mm108** [comment]
> > hi, is there any update on this?
> > I made an update using lvgl 8.2, you could see below link as reference.
> > https://github.com/rillhu/Nscreen_32.git
> 
> And I also hope there will be offical update from Nscreen.

Cool, thanks.
