### ISSUE TITLE
How to enable touch in landscape position in Nscreen_32

### ISSUE THREAD

**Issue by UmangSuthar101** [yeacreate-opensources/Nscreen_32#4]
Greetings,

I tried to contact you, but didn't get any response from you!!

I request you to support me with How can I enable the touch in the landscape position in Nscreen_32?

Because my application needs a landscape position and I able to rotate the content of the screen but can't be able to touch in that position!!!!

Help me with that ASAP it's urgent!!!

**Comment by simonchen007** [comment]
For the touch in the landscape position, which value(number) do I have to write?
https://github.com/yeacreate-opensources/Nscreen_32/blob/master/lvgl_demo/src/gt911.h#L49
