### ISSUE TITLE
Missed information about the brightness for the display

### ISSUE THREAD

**Issue by ajsb85** [yeacreate-opensources/Nscreen_32#5]
**Display**

- Resolution 480x320
- Display size 4.0”
- Color depth 16 bit, RGB565
- Technology TN
- DPI 144 px/inch
- Touch pad Capcitive (Goodix GT911)
- Brightness 260cd/㎡
- Interface Parallel 8 bit (ST7796)

Cheers @simonchen007

**Comment by simonchen007** [comment]
the Brightness is 260cd/㎡

**Comment by ajsb85** [comment]
Hi, @simonchen007 

What is the manufacturing part number for the display?
